---
spring:
  profiles: subject
  application:
    name: subject
words: I,You,He,She,It
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-primary:8017/eureka},${EUREKA_URI:http://eureka-secondary:8018/eureka/},${EUREKA_URI:http://eureka-tertiary:8019/eureka/}
    registerWithEureka: true
    #    fetchRegistry: true
    should-unregister-on-shutdown: true
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20

---
spring:
  profiles: verb
  application:
    name: verb
words: ran,knew,had,saw,bought
server:
  port: 8012
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-primary:8017/eureka},${EUREKA_URI:http://eureka-secondary:8018/eureka/},${EUREKA_URI:http://eureka-tertiary:8019/eureka/}
    registerWithEureka: true
    #    fetchRegistry: true
    should-unregister-on-shutdown: true
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20

---
spring:
  profiles: article
  application:
    name: article
words: a,the
server:
  port: 8013
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-primary:8017/eureka},${EUREKA_URI:http://eureka-secondary:8018/eureka/},${EUREKA_URI:http://eureka-tertiary:8019/eureka/}
    registerWithEureka: true
    #    fetchRegistry: true
    should-unregister-on-shutdown: true
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20

---
spring:
  profiles: adjective
  application:
    name: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: 8014
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-primary:8017/eureka},${EUREKA_URI:http://eureka-secondary:8018/eureka/},${EUREKA_URI:http://eureka-tertiary:8019/eureka/}
    registerWithEureka: true
    #    fetchRegistry: true
    should-unregister-on-shutdown: true
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20

---
spring:
  profiles: noun
  application:
    name: noun
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: 8015
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-primary:8017/eureka},${EUREKA_URI:http://eureka-secondary:8018/eureka/},${EUREKA_URI:http://eureka-tertiary:8019/eureka/}
    registerWithEureka: true
    #    fetchRegistry: true
    should-unregister-on-shutdown: true
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  
---
spring:
  profiles: cold-noun
  application:
    name: noun
words: icicle,refrigerator,blizzard,snowball
server:
  port: 8016
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-primary:8017/eureka},${EUREKA_URI:http://eureka-secondary:8018/eureka/},${EUREKA_URI:http://eureka-tertiary:8019/eureka/}
    registerWithEureka: true
    #    fetchRegistry: true
    should-unregister-on-shutdown: true
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20

---
spring:
  profiles: default
  application:
    name: lab-9-gateway
server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-primary:8017/eureka},${EUREKA_URI:http://eureka-secondary:8018/eureka/},${EUREKA_URI:http://eureka-tertiary:8019/eureka/}
    registerWithEureka: true
    #    fetchRegistry: true
    should-unregister-on-shutdown: true
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
